/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package cb_homework1;

import java.util.Scanner;
import javax.swing.JOptionPane;

/**
 *
 * @author Otto
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow
     */
    MatrixPP mpp;
    
    
    public MainWindow() {
        initComponents();
        
        Scanner sc = new Scanner(System.in);
        
        String strSequence1 = "g,a,a,t,t,c,a,g,t,t,a";
        String strSequence2 = "g,g,a,t,c,g,a";
//        String strSequence1 = "g,a,a,t,t,c,a,g,t,t,a,c,g,t,a,t,a,c,a,g,a";
//        String strSequence2 = "g,g,a,t,c,g,a,c,c,a,t,t,c,g,c,a,c,g,t,t,a";        
                
//        String strSequence1 = "";
//        String strSequence2 = "";        
        
//        //The user inserts the first sequence
//        System.out.println("Enter sequence 1");
//        //We get the first sequence
//        strSequence1 = input.next();
//        
//        //The user inserts the second sequence
//        System.out.println("Enter sequence 2");
//        //We get the first sequence
//        strSequence2 = input.next();

//        System.out.print("Please enter your first sequence: ");
//        String strSequence1 = sc.nextLine();
//        System.out.print("Enter your second sequence: ");
//        String strSequence2 = sc.nextLine();        
        
        //We print both sequences                                               
        //We create the matrix
        mpp = new MatrixPP(strSequence1, strSequence2);        
        
        //We put the values in the textboxes
        this.txtMatch.setText(""+mpp.misMatchGood);
        this.txtMismatch.setText(""+mpp.misMatchBad);
        this.txtPenalization.setText(""+mpp.gapPenalty);
        
        //Now the sequences
        String temp = "";
        for (String str : mpp.sequence1) {
            temp += "," + str;
        }//End for (String str : mpp.sequence1)
        temp = temp.replaceFirst(",", "");
        
        this.txtSequence1.setText(temp);
        
        temp = "";
        for (String str : mpp.sequence2) {
            temp += "," + str;
        }//End for (String str : mpp.sequence2)
        temp = temp.replaceFirst(",", "");        
        this.txtSequence2.setText(temp);
               
    }//End public MainWindow()

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        lblMatch = new javax.swing.JLabel();
        txtMatch = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        lblMismatch = new javax.swing.JLabel();
        txtMismatch = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        lblGapPanalty = new javax.swing.JLabel();
        txtPenalization = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        lblSequence1 = new javax.swing.JLabel();
        txtSequence1 = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        lblSequence2 = new javax.swing.JLabel();
        txtSequence2 = new javax.swing.JTextField();
        btnExecute = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        Tab = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAResult = new javax.swing.JTextArea();

        jLabel5.setText("jLabel5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Needleman/Wunsch Technique");
        setPreferredSize(new java.awt.Dimension(900, 800));
        getContentPane().setLayout(new java.awt.GridLayout(3, 0, 10, 10));

        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        jPanel3.setLayout(new java.awt.GridLayout(1, 0));

        lblMatch.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblMatch.setText("Match");
        jPanel3.add(lblMatch);

        txtMatch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMatchActionPerformed(evt);
            }
        });
        jPanel3.add(txtMatch);

        jPanel1.add(jPanel3);

        jPanel4.setLayout(new java.awt.GridLayout(1, 0));

        lblMismatch.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblMismatch.setText("Mismatch");
        jPanel4.add(lblMismatch);
        jPanel4.add(txtMismatch);

        jPanel1.add(jPanel4);

        jPanel5.setLayout(new java.awt.GridLayout(1, 0));

        lblGapPanalty.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblGapPanalty.setText("Gap Penalty");
        jPanel5.add(lblGapPanalty);
        jPanel5.add(txtPenalization);

        jPanel1.add(jPanel5);

        getContentPane().add(jPanel1);

        jPanel2.setLayout(new java.awt.GridLayout(3, 0, 0, 10));

        jPanel7.setLayout(new java.awt.GridLayout(1, 0));

        lblSequence1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblSequence1.setText("Sequence 1");
        jPanel7.add(lblSequence1);
        jPanel7.add(txtSequence1);

        jPanel2.add(jPanel7);

        jPanel8.setLayout(new java.awt.GridLayout(1, 0, 0, 10));

        lblSequence2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblSequence2.setText("Sequence 2");
        jPanel8.add(lblSequence2);

        txtSequence2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSequence2ActionPerformed(evt);
            }
        });
        jPanel8.add(txtSequence2);

        jPanel2.add(jPanel8);

        btnExecute.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnExecute.setText("Execute");
        btnExecute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExecuteActionPerformed(evt);
            }
        });
        jPanel2.add(btnExecute);

        getContentPane().add(jPanel2);

        jPanel6.setLayout(new java.awt.GridLayout(1, 0));

        txtAResult.setEditable(false);
        txtAResult.setColumns(20);
        txtAResult.setRows(5);
        jScrollPane1.setViewportView(txtAResult);

        Tab.addTab("tab1", jScrollPane1);

        jPanel6.add(Tab);

        getContentPane().add(jPanel6);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMatchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMatchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMatchActionPerformed

    private void txtSequence2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSequence2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSequence2ActionPerformed

    private void btnExecuteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExecuteActionPerformed
        // TODO add your handling code here:
        this.txtAResult.setText("");
        
        //We execute te algorithm to get the answer
        //First we get the sequences from the textboxes
        String seq1 = this.txtSequence1.getText();
        String seq2 = this.txtSequence2.getText();
        
        //Then we execute and show the answer
        //Validations Match
        int match, mismatch, penalty;
        try {
        
            match = Integer.parseInt(this.txtMatch.getText());
        
        } catch (Exception ex){
        
            JOptionPane.showMessageDialog(this, "Match must be an integer.", "Match Not Integer", JOptionPane.ERROR_MESSAGE);
            return;
        
        }//End catch (Exception ex)
        
        //Validations Mismatch
        try {
        
            mismatch = Integer.parseInt(this.txtMismatch.getText());
        
        } catch (Exception ex){
        
            JOptionPane.showMessageDialog(this, "Mismatch must be an integer.", "Mismatch Not Integer", JOptionPane.ERROR_MESSAGE);
            return;
        
        }//End catch (Exception ex)        

        //Validations Mismatch
        try {
        
            penalty = Integer.parseInt(this.txtPenalization.getText());
        
        } catch (Exception ex){
        
            JOptionPane.showMessageDialog(this, "Gap Penalty must be an integer.", "Gap Penalty Not Integer", JOptionPane.ERROR_MESSAGE);
            return;
        
        }//End catch (Exception ex)        
        
        String sq1 = this.txtSequence1.getText();
        String sq2 = this.txtSequence2.getText();
        
        this.mpp.execute(sq1, sq2, match, mismatch, penalty);
        
        this.txtAResult.append(this.mpp.sMatrix);
        
        this.txtAResult.append(this.mpp.sFinalAlignment);
        
    }//GEN-LAST:event_btnExecuteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane Tab;
    private javax.swing.JButton btnExecute;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblGapPanalty;
    private javax.swing.JLabel lblMatch;
    private javax.swing.JLabel lblMismatch;
    private javax.swing.JLabel lblSequence1;
    private javax.swing.JLabel lblSequence2;
    private javax.swing.JTextArea txtAResult;
    private javax.swing.JTextField txtMatch;
    private javax.swing.JTextField txtMismatch;
    private javax.swing.JTextField txtPenalization;
    private javax.swing.JTextField txtSequence1;
    private javax.swing.JTextField txtSequence2;
    // End of variables declaration//GEN-END:variables
}
